### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

### ISSUE THREAD

**Issue by gauraviiita** [concept-graphs/concept-graphs#3] opened 2023-10-08 11:39 UTC
Hi @krrish94, @georgegu1997 

Thank you for support for the last issues. Now, I am trying to run the following command but getting an error related to requests. 
python scripts/generate_gsa_results.py \
    --dataset_root /home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica \
    --dataset_config /home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml \
    --scene_id room0 \
    --class_set none \
    --stride 5

The error is as follows:

(conceptgraph) gaurav@gaurav-GF65-Thin-10UE:~/Desktop/Robotics/concept-graphs/conceptgraph$ python scripts/generate_gsa_results.py \
    --dataset_root /home/gaurav/Desktop/Robotics/concept-graphs/Datasets/Replica \
    --dataset_config /home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/dataset/dataconfigs/replica/replica.yaml \
    --scene_id room0 \
    --class_set none \
    --stride 5
/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warn(f"Failed to load image Python extension: {e}")
[2023-10-08 16:58:06,002] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
final text_encoder_type: bert-base-uncased
Downloading (…)ip_pytorch_model.bin:  10%|██████████                                                                                       | 409M/3.94G [01:28<11:14, 5.24MB/s]Traceback (most recent call last):
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/urllib3/response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/urllib3/response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/urllib3/response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/urllib3/response.py", line 566, in read
    with self._error_catcher():
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/urllib3/response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/scripts/generate_gsa_results.py", line 652, in <module>
    main(args)
  File "/home/gaurav/Desktop/Robotics/concept-graphs/conceptgraph/scripts/generate_gsa_results.py", line 382, in main
    clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/open_clip/factory.py", line 308, in create_model_and_transforms
    model = create_model(
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/open_clip/factory.py", line 222, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/open_clip/pretrained.py", line 425, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/open_clip/pretrained.py", line 395, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 541, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "/home/gaurav/conda/envs/conceptgraph/lib/python3.10/site-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading (…)ip_pytorch_model.bin:  10%|██████████

**Comment by krrish94** [comment] 2023-10-08 12:06
This looks like a huggingface error and not with concept-graphs?

See https://discuss.huggingface.co/t/out-of-no-where-requests-exceptions-readtimeout-httpsconnectionpool-host-huggingface-co-port-443-read-timed-out/43148/12

Closing this -- feel free to re-open if the issue is infact with the repo and not on the huggingface side.

**Closed by krrish94** 2023-10-08 12:06 UTC
